### ISSUE TITLE
Project RoadMap

### ISSUE THREAD

**Issue by BattutDev** [BattutDev/choucroutejs#7]
## Project Roadmap:

- [ ] Session
	- [ ] Extendable store
	- [ ] Default Redis store

- [ ] Cors (Cross-origin resource sharing)

- [ ] Router (a controller-like)
